---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: external-dns-secret
  namespace: infrastructure
spec:
  encryptedData:
    CF_API_EMAIL: AgBCkn+0Kl4YcsYY9Ni2nJf782XkyM21x4Y5RoxssaEcLaZBSt+dKFnLdmeEAe8HCBNdUdezstZwVHqX1zsi7ljFRLFa4tsESkeQQnD5yvKxFDQJBwF0zm2W3t2m2mCvxtHk1rTAyRLlo5KyQuhnPYuMqZ27lBpCo1GsluVQc6gXa1Py+fvaIW4NLLiZMIegAtOdx07MPoZ9kGdb7AbKqJgjEe+EBAQsZlekl2+ZXaj3LnmWQDwbyi4/LiffDHR7v6cj5dRHCFqz+W0cleprSQ+EEoe/Wtlnto4czAwCrted6CBC7YtpLY3aW/oeYxrulGFOY/9gRsMPSImhV3jDWnqbppq+YooB6+nvVu2njRY8YEZOqudJZTMm+7N6ZL0JEexbhwZRTXhXno/Q5nQHq9oL6t5T7t8jel7V6hd35SZniScFp0HYCMHdQwogwgMz4+tMxvcOFmmVBI3IAlkVHDFC0UNMkIEORGWJxrRkxKVkEsixXXTqxucEOIpGf4s/VJyQIWZMAjp13JtH2szDyCtSr34cKpu8kw9G0rbZAyCl2bjz/86Vs/OK2mGBOooxTygGWFlDXXNOkxQm5MOy2b8GY1HL1MdlZp+qASIfzIozdFWuH5IZnyGUcZyWsba1Ph462vU0pkW2qBfi3Rs7bgDBapJOjWswvRfQDln0B2hpXOKx0WA57UkwOA00wTpNh8ZkZOM2g3/h5KaRYc3D8goikQ==
    CF_API_KEY: AgCW3G8Hbf4PaS0xBqZ0CydfEXTTujeJzZYZWBSjsH6//K1Vn+0FOuFp/YNF3JxYKV/+O96iRkNkLe4ehHOPKlCBtjV5/lN4tguY0dOmGpIgIN/NZfGXyIKroYOqV/nJInHCVx5EMy1rkLHxCpmhAGRul8YtBP7yT+vPAGwMfS5KuOvG7L1o/06XzR9fNgNT2r9S99TfG8bOtH4rw0OGEB3c8iKQSgkGUOu8ssHQmBXHfpeclfIrCLkk6uVq9QZwSz0kkuIGWgR++hbsPEvxL+UcF/G023AhA6d/RGqxTpJYLNgDV756vGNtGitgyCvRpXTzCZzMfFfPLr/AkDhV39ke+IkPfpxQu7bVC3jsOjhlroW4IROX66ylfFZI0uFLHyb4gRyUdy38+azfb32hQFPbrDjaQ+Gvb3Q8/vxlDgNq3bc6wYAIB3uxeP4cTfPOOselgOpqHa2Cx+EhsihZWfnaRkifXMbLyx6zZA/3KwFC7AaUsqK/Nqgn92AEseIzSBRJSr3VU29Vf3FkzVQljxA2idNqWBZd0iaA/8gQESPDjuFFy9hpd1qpyjAh4fvCM2JWYg6AAUiBIyuf954o5CXf/dyzlc/xnoq/mRsebAfKclqfavPtrVueN6YD5T9tNLmtfpcWnaM6vOJCtu3NNEs7mTNjPSwRojqpD/dcW2lP3kvmQPmo6fV7BOMIxrXy/yr36bNTpM3f5gUAOtjNQMqCWUTLDk11CoBHnVVfSGigyarXm8e7
  template:
    metadata:
      name: external-dns-secret
      namespace: infrastructure
    type: Opaque
