apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: external-dns-secret
  namespace: infrastructure
spec:
  type: kv-v2
  mount: kv
  path: clusters/dell7040/infrastructure/external-dns
  destination:
    name: external-dns-secret
    create: true
  refreshAfter: 30s
  rolloutRestartTargets:
    - kind: Deployment
      name: external-dns
  hmacSecretData: true
  vaultAuthRef: external-dns-vault-auth