apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - selfsigned-bootstrap-clusterissuer.yaml
  - vault-internal-root-ca-certificate.yaml
  - vault-internal-ca-clusterissuer.yaml
  - vault-internal-tls-certificate.yaml
  - vault-gateway.yaml
  - vault-httproute.yaml
helmCharts:
  - name: vault
    version: 0.32.0
    releaseName: vault
    repo: https://helm.releases.hashicorp.com
    valuesFile: values.yaml
    namespace: vault
