apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-internal-root-ca
  namespace: infrastructure
spec:
  commonName: vault-internal-root-ca
  isCA: true
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-bootstrap
  secretName: vault-internal-root-ca
