apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-internal-tls
  namespace: vault
spec:
  commonName: vault.lab.definit.co.uk
  dnsNames:
    - vault.lab.definit.co.uk
    - vault.vault.svc
    - vault.vault.svc.cluster.local
    - vault-active.vault.svc
    - vault-active.vault.svc.cluster.local
    - vault-0.vault-internal.vault.svc
    - vault-1.vault-internal.vault.svc
    - vault-2.vault-internal.vault.svc
  issuerRef:
    kind: ClusterIssuer
    name: vault-internal-ca
  secretName: vault-internal-tls
