apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infrastructure
helmCharts:
  - name: cloudnative-pg
    version: 0.28.0
    releaseName: cnpg
    repo: https://cloudnative-pg.github.io/charts
    valuesFile: values.yaml
    namespace: infrastructure
