apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - vault-token-sealedsecret.yaml
  - tfe-token-sealedsecret.yaml
patches:
  # - path: terraform-mcp-securitycontext-patch.yaml
  #   target:
  #     kind: Deployment
  #     name: hashicorp-mcp-terraform-mcp
  - path: vault-mcp-securitycontext-patch.yaml
    target:
      kind: Deployment
      name: hashicorp-mcp-vault-mcp-deployment
