---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tfe-token-secret
  namespace: mcp-servers
spec:
  encryptedData:
    token: AgBzUNGY+mOv6FH3IncpWXFrveNDlCNyeaboTaJkCoFnxn11r7OpPlWeu8X5wDwQ3LYyolNqhd74kuZ1/7p3ms7C1VBsFAb2mN0Qt8/TWRZ4X0meGe48WSdjxtIdKU1rA0N8Djn6iGPgwbqi7LbCDIViDi+YOvHcPEXGBJ4pjOtHMR7v8T/ThHO9avBca3w43YWa9K4vFL6oqWW9axs+iV5Ij1tK46uD1Aw0iMSYO2MUnhLP57+qRGp9/NXyG5SmV9OFShOiOm2a9XinIjUo2vh8o+7tfNbX9hrrkvUnxZ22bhU0XberS2jSuVah1Ld9otUWx+hglv+q/KRn97UqScWcikxH5HCc2wOHRXtFOvh57Lo+KUJGlOpRvYTDLlILwl/2fU6UTBep0jxsPpmSbZT4DLJCkWcU9B+SZzmD4yMob2sXaMDN6AAdxITseyU4IuSRCr0nC6IafngyB/xYTdW+jCE0Q2xLxoHaABSsP3bWp2DAk1SdU8V4SDfXblHLi0qFvGMnblm6STXlC+6BiwtuBKVcSk4OkVdrkYsZ/atre8VcoB2syKezw2XN2BWsKqjxEGj0uAAwoT9njFUWfYui0SNpCZ007Mn0efSTD41eIqrG0NDCj0/E+MYEABQK7zFMbSsRwzgnhjFlxXBfCV5RwmS70fmEi1tbUyMiF9xchl41z+2033ABnTKIxh7qMNWJtTOPlL3HEcNtrwOFI7E5MO4j8PzvlKr58p4FE4L6wJw/9dj46X2HCPnmQvuwZFM63L/4UYukNctJAlgNPVKrxwHNI0UcrB1lcmuas0n3Wm+C9eakpVKNwvQ=
  template:
    metadata:
      name: tfe-token-secret
      namespace: mcp-servers
