---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tfe-token-secret
  namespace: mcp-servers
spec:
  encryptedData:
    TFE_TOKEN: AgCgPBW4Rxg7wfo4VZ7IhdT/XBcCCBaxV9jcHyu+7hAz/SyxHhVL9h6WC9KoFZpqLqvry04AhyN6gmJLjHgts3Z0qd49AhNy2DB9FmEYTOrS8K2YAcgasipJinSgAEPaqanMNoEsiBIWAjA19YZDITSZ+eTedqs7MTchxqv8VkJ0EsslkKyF8yx3HJncaIhYBvDJYOb0fKytJibgwj0Fuk97s9jO6v1agOLcxuKL/OSgTTq8IFimu39ntQWxiKlAzI0xPZW8vsWRIjiG1Rb6blefAsdx0ZTJf28vzwOgdgS5mJLMNPBMDJwjHcydEZkHlVkqfqKZQP+g2ocC8c+bFDHJtQEemycCC7AfPVYqPXwgi5bDdK+WwdLVRCE2xh/McpuFb64iQha8xVIPFwkJ3ezpxlnt0AwF8Vyb8ndEFxe64cmPEEFCemSW21jrDTbnCHuIGhAEirPdK5NW0tAspSfrebDYS7kHuCpWdI7Fx52Qc4amWxQm/ExaKRpaiaaprgY3zlq9kGL6fZG8lsGClI5hVpTFwLQMLT7gUOwiNHiByLi3uDmzAjgjrLcTupE5g+5YauP4v5ejEO05pfgz1F9ylVd1BOFQFD6hnLufUt9XtXv2yAGk9PQ59BVpMmHEqXQ9UKt9hpYiLq9KsuitOzzA36Uq85daVIWxXsdtZSEpsYhA9h9kslOtqNbJQtZrup4+BFhBiZKY3j/R0g5fKxYLi1XWJhw35/3oB0GhJBOH6jZHuBUHr11tI0Cp4L6CI3yqLjFig5bU9pEb3XdDbxDxWZ3nIP8DGHEa9padbVKoWlA76pebUEdHV34=
  template:
    metadata:
      name: tfe-token-secret
      namespace: mcp-servers
