---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vault-token-secret
  namespace: mcp-servers
spec:
  encryptedData:
    VAULT_TOKEN: AgCFZQSSsk9SjkZApEfb0+/v041BI844OV75IoIOvKpcIMmgugaLVDG2BfGSGJ8vxJQsgX8fHxiDUdqnSg1ULPEPXpO0xMqxRh1hiC0lu/1Gs5bio1CRwVXAUDXDaCVio1pnqi3CmhPpaMDOpOtkKEjvdGdIGqoflKVGIgaLeeVFf+/q2k3R7qGBghobSkjnEuCqNHl/oEs/MGp1YBx0xgiO0Bl3pP+N3xifwioHPkSLO2O90Ev8fy5sn9aZHj1ZkqjBvKKnEWvZ6/gRtY+6Fxs5Pmix/NyNyJ0J+yjYzqK4cVfrPNf9vmN3SbptYHTcXXKsksmfY5Xx+a0X+gLb69iEmK+iOXWqf/if+FQHbES4T1h5vRF9oIKRMPZlaKheJ15L+Ajt5An/SJ1ri5JIe3X0+yFNkau/Yi1BMjHWrjZGn+UNm6CSezMn8FtgHXYeLCZ3F6K+xxCMoTpYerLk5jYG71FmYY6E4a3LTfuMmtLCxNhdlqoh4ReVHwioCE0/+oVkv5zYLhLddgfBBI6t1eY+G1D04xv67oZUIR8y65a8ELFk7PbZZD+F5Ft5iTRJmtPX7WiMOWpQGvFBBPHHddBcqpWMmWXoYS9TQR7fAWlP5PcWGo5S36/cRRLekmJ/AJBn1OHjTQ5G736F6+7si6BAT8GyveVqbRnvpVoCAOnmH1TFhLqMV+TdWNL1Ber9+1Ia20ecgTa8gzOqMbZfvbh916N85K/YjZgZPsEFqv0NHzzWcWQcikEViCHpt9O9XVGjNnJHbzygeSoD4+wTZHOQ4rSjaWTkRb0NadJGcabSP2veVZejIkbyG9FB2bKu3Q==
  template:
    metadata:
      name: vault-token-secret
      namespace: mcp-servers
