---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vault-token-secret
  namespace: mcp-servers
spec:
  encryptedData:
    token: AgBLCObgOROEJZqPze18oL+wtYIA/BbVWJyhqwmCbh0ISzqA7nk8Qeil1Ee4cARitJX+qwqqukGWS3vMWD5lfxQyJ9B/1u/IHB/5pMmAOAPPsN60AZpDLz71FGLVc9GWHlP9o3glN3OrSY1f1U6vb5GWPc9bq5XVy51amTVjRpYlFgcuel1ME1jwaKu+7kcOItcku6sMYvGZ1WwjEPttU9dadL2/lXPc/JLpkmtSuon6+WYkDNadSmFJjX5weoD4RxI9JFY/17JqA+6e6CnVek1UCFIeYlDOQRMsj23q/WBu28Lao37yO5ZoG3d9mVevQVdG9vIVIapLYy/Sji8Iw+dfUIMwkAMnAO/xESEVplUE03A2Smf4z4QUAXG+LjeuE29YMgnunVJn/jLVg1enDY/3UOEgnnk2fxT2oSIAElZTBCd/TPu5RHA/UoAJs9KmPjtgTin43+6TnCzWMczdvYW8MqDe6FxXM1jL+8B+hBfBgL9fNTZZnM5IofBtrC81eO30DhCWevDvl2GsEtuSJejkgp7sDXylSdcfZCZg+oOoKaOC92Z6jZVNCezRlYowqaKAHfoshJArlTW9AsCmZPHxnXw2IwB9nJUTeTVva70nRdlTS0U9gDOxj+eNaleiCD2RdpaoJuyMyTcOsT7F0+oiJcvLB7tA4HlIazSI2kH+VYfcvePIERL5n6pRFzSKaqofJkVzemB/0vRxGHblJHhO+o47TXb/qEAIzA7zJ8T59N3S+nI3KaMlPH61VyangiFVRQso1ThMfSXR/Lrjnd+i/LDL+U8pLEEyE7A4utwDNYt+ouZxQeomUzDgaAER3Q==
  template:
    metadata:
      name: vault-token-secret
      namespace: mcp-servers
