apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mcp-servers
helmCharts:
  - name: hashicorp-mcp
    version: 0.2.2
    releaseName: hashicorp-mcp
    repo: https://sammcgeown.github.io/hashicorp-mcp-servers-helm/
    valuesFile: values.yaml
    namespace: mcp-servers
