---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secrets
  namespace: monitoring
spec:
  encryptedData:
    grafana-admin-password: AgACZpKT1Gdc23rM1xPBAwsRvHTYbj5TDyH8lKPHT0rBgGlDRwks56jRoKnvgb4naHrO5yavT2s7CJ7D1wRgLNGEj0DPjndrnjJBuEoIx76Qan20cURuM7sXd4WsPG91Hbp6nMKR2fJocGspgOMCQKUgz/B8tLf5pWwAK871hkg55vBbnyar4sb+yVRTAvY+WfzY3VMxa72IAXS4xBGQaYKaHvXB470klEeYC4+xBjTZfNH58x4OIrLmdkKv0ob++WaCyZ8DUkWkzd61zlm4hvZrOGw04amI+wXGODTy/yPh6HMnLcCMcvwReUic50j984H2JgnV6Wrx6kER+uZ4oAafxHD/ahJp5iB5bcAca9fnVk8FFu+f7Mk85X4ap580ezkFVjKlTecw5DfN31YBMg4djRef9kCy2AzhVcOfA5SpcmrMiVxLVFkwC+RkTIYJ1EXbsiYDwoDM1NaiIeNZFdfVTWH7nqOvoB3a5etQhip6Bvfd03/Nh/pWLahZOsnG8eE3lAXFo2zZKrbJmXgjKN9H9j5hl8QVhVc8gCMvB3D6qiM2U35JelrDlegOOckhv+m0HknlmiuG0khsqPEE6jZ/XaI0V4zwXjOBlb/yo9hl3oqQ7qPnNvrFoV7skxd6upkIzK22/10fDqCDzCf2f5ZD0nL87mnwPBPhf/bX6+OBWlO1XJfnDWI1WgXIvkm3ePEz+cb09Wty4A==
    grafana-admin-user: AgAQ2/RDx+zAhh5sNXm2vC7YlHnQfMeJNHgWvmWYaR9L1BZ9SFWytuWmEGuo3BD2LPiUkp0ivt2gSlrEa+8/y6sdCxtg8Ohb75rhUdacuF7vWkrMev0A4HqP3M2sCB906WIbS3LxpIYJ7oN9Fq257sMC702cNf6kKk4VYWiBkTyRUDjM7YaGgmRX4zs+Z6t+/PHZ0t+RuhaNyAGlWVPCXF42rcEcZYtzKLUizfLXU1WXfpcLx1eI+w0z5G0ipW+fsPECrw53fuV4g7GvlEobqPpicutYxAg6q2orl8Mqki6cpa2ikb8c4c8SLt03t9ix5a06FizC5/Z4Adx4mAwLAAmgAjFMlKteAfiO/QlVqun0mx/V5a6HJDaR6z1lvg7Vgg8UirQoD9g9pGXcFKHaaYQTL6sfDkSEiU+uMfBbcw2q95rqarxN+JZAwlZ+G6Lfr0XmsZFPDKujzvZjQh1OLbnFtc7CAeC4xtcLBLMGRdbzLwNsZ48R3xl4G+O/Rq/M3cKJzGNOQTa2dg3CzEQPdf9c7/4vjmol8jydBlx3RS3MzcoQDFxXeviF0Ss2zNfeuQHubU2HrxBg1iWtq1Y52m40jGIsmJlSyocUV4nuw9YFt46+pYXllr5Ai6Re1NPyBrVfYZOHmPcHTDi0NAMDGqLx+kIqk40ay5V/HY/vliNi0ieY4vpzvLTo5GNlQoaOVG+TYfw=
  template:
    metadata:
      name: grafana-secrets
      namespace: monitoring
