---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secrets
  namespace: monitoring
spec:
  encryptedData:
    grafana-admin-password: AgB0nd+dZ976iD44E/Rv5pfdCrtlAFelHLtSvxfF31GZp2q18sSFWs2Q+Yh2B866XBGZ29QXrD3iaKCHdbqGcGvjSDhulWujqNg1StfJX4cwL/H1eV+7Y6Mlg8gs5xceGLZzZlbGIOkGIJZyJiVaCU1WcFFYKvgOA81d4pCOX60hxUrg2ONfpcSm+6BqNQ3wtoufIzRjyL6FPNdypI2uHoFPWDU6tFou16lPEh7v4tnoe5xMhPKaqoZbR5ofapkuyLMhNlxayo8w8JW50z6EWZwbnIIa1s4a5udzgCI/XnyUojJZZOkq3Tgp5kXnEkVNmZzWwaHZdF2n+/qezUPc+HtZO2GECkjzJMUaTbjjISaU1JizLaQgo2or+/VBoN9z+YgN1YMSU6JpvAJqieFE/bcHRS8LQ6Cgb9G2whTEAGn9NWv+OB5Bid7ktvNozhLVOt+Pn+QwHFK1ihS1hvOGR2xuuslGIxVBSTYoz2V1VW1qt5xr3g09Y/ppl44eEhu7jBmZX3gdjrn/l4oS83tAYgOjfKM/E2ioJRLG19pTN1rV9efle9N/izSD3ZMBL3CpyObBM7z5D8AD1nQBO7klHSJG+ULstoZxC9csJHirVJCJIEq7/2Ek/0Z7uJA054ykUklLxUcShK15IjRkyJ1ba32hvYHiJhFwlKtUXfnmgN6ufx5XqLLDVEm+DBp2Wam9NqBIEjqgDHNyX5ZOKc9GFaHa1+7SGg==
    grafana-admin-user: AgCDSU2FkO/rIGrmSGoHvUQn48zw2Lz/smDJFex+sQEj1nTHd55+RQNszk3JUODFBcKxXwzJzFE52FoIVK1DJ4H9IBwaKKIG7BSBd6XFZITCSN2BRzFSFgXmWR09msPDcUdkxfCiYG/rvruU1r4j1+On8m92xJxC2jrV7W8y8bSEvUexYkPRaW9GteSFK6YT4mEaYCH6p2JgEjud+RYqM+MnX9Sn3Hvd9bwSSg8YNRc9RTJDs94fNUGvR//wIH/7AVWzG4ixhuOM40X5SuQ/BUgOKKfQRjyAQJWUA+MO+vvq0w+HzaZd6oY68YM/nvIWoLPAOF04VkX1tAz7ubAr+m04SVwmoURY89j0XyyjGpv4iSNYwYQYOY7h/7c6hW3EitMDUOxxD2BbM1gPI6JeGsxRxeftOYRwd5mfzwlMJ5/nx75yCx2NCyREbANx9GgqbBVO/uYFt4nN/Ugc3l2pNYBx1VUqghsXDQ1JgN2y1fKwAZN6yW3d7yOwKsp19729imBX1+a+mlOeKODB2CZYWwWsrzC1vTSXAe0yHT3hVYXtoxMNCxYFaLqQgdE8fS4ACHd0THvaxkvfqWN3e9X8YXJyP/nUdSn1Kbm7yn+QOT0lqYwwmLNrk/Vo17n2TGQZYp2TA9xokoRhgoR4i/lJ53qHPcY2voFra4LrA5EpI2kAgo6o+QpO4IEgmyyvMoTlbHjPmoh3A46zbPLKQxfg
  template:
    metadata:
      name: grafana-secrets
      namespace: monitoring
