apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: vault-secrets-operator
    version: 1.4.0
    releaseName: vault-secrets-operator
    repo: https://helm.releases.hashicorp.com
    namespace: vault-secrets-operator
    valuesInline:
      csi:
        enabled: true
      defaultVaultConnection:
        enabled: true
        address: "http://vault.vault.svc.cluster.local:8200"
        skipTLSVerify: false
      controller:
        manager:
          clientCache:
            persistenceModel: direct-encrypted
            storageEncryption:
              enabled: true
              mount: kubernetes
              keyName: vso-client-cache
              transitMount: transit-mount
              kubernetes:
                role: auth-role-operator
                namespace: vault-secrets-operator
                serviceAccount: vault-secrets-operator-controller-manager
                tokenAudiences: ["vault"]