apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: vault-secrets-operator
    version: 1.4.0
    releaseName: vault-secrets-operator
    repo: https://helm.releases.hashicorp.com
    namespace: vault-secrets-operator
