apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hashicorp-mcp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/sammcgeown/kubernetes-clusters.git
    targetRevision: main
    path: hashicorp-mcp/overlays/dell7040
  destination:
    server: https://kubernetes.default.svc
    namespace: mcp-servers
  ignoreDifferences:
    - group: gateway.networking.k8s.io
      kind: Gateway
      jqPathExpressions:
        - .spec.listeners[].allowedRoutes
        - .spec.listeners[].tls.certificateRefs[].group
        - .spec.listeners[].tls.certificateRefs[].kind
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jqPathExpressions:
        - .spec.rules[].backendRefs[].group
        - .spec.rules[].backendRefs[].kind
        - .spec.rules[].backendRefs[].weight
        - .spec.parentRefs[].group
        - .spec.parentRefs[].kind
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
