---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: infrastructure
spec:
  encryptedData:
    api-token: AgAU27Gigu9oKEChqdQ+KeK/HsnH2V4zEp4UYEPR+1Qf0UQyh48Pn2iZPlTpZ/b6djoIgn4nkH/ENnACr3FU5hZotk4jUL/5i7ugtyU7BTK0Syh1tYG6DGQzkETteCzVGTG25ijW1bzXRmMKAET4sYxRkp9RUMxDKBcWBZWLfaAal6R+NJvSLkBZcUfii9/+0eFrdJ41rwauB5yoTGnQ60f6DAShxE8ukwmrwdo8x6Td6+86hN3UADIG556Kjsk3AjfGL5yviY/XdWkiNxfBIBfHgZmK/SjrQ8NZNCiCt59xCMSqjlk/9POMVmKxVekCUcsoMVz8Bj97tcBU1KWQ1G4KCf9Uy34RZeF1ICZvGUyqmJWJLCuS+G7iXd+fPkoyKWPIc/l/Z+IXAfvKEyVI9lNBopOJA7ACfvQv2wHwP7CbDV5u2IapHfCJQXminZKEwqPhi3fjRXer1ac1X8dziM1yQrgyWFtRhlfMaYrsrZMLaLNERV8LGxng7a2+4tfFY4n0OqMKAj3SomA628OGUufGlFAxXgRgc1UCBSr3zRNA0bGnhuiuRRc4NyzX0P248//zGvL/POAcBE2Urat0xiVBcvX7IJGg9b8mH3qq7WtyV6aqEpLx021iWsvbAg87FZR8rm2+EL3waYfDfNktt65sj3vK2oSeyniyQ2hjrF3mgOlz63d4kM6sJXcKqMdwb33jeuQBMrB5vkVMhJUnvedLmcMWKbPsEPABvvDiF+gF2a73l4Ik8LSN
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: infrastructure
    type: Opaque
