apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: infrastructure
spec:
  type: kv-v2
  mount: kv
  path: clusters/dell7040/infrastructure/cert-manager
  destination:
    name: cloudflare-api-token-secret
    create: true
  refreshAfter: 30s
  vaultAuthRef: cert-manager-vault-auth