apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: infrastructure
spec:
  type: kv-v2

  # mount path
  mount: kv

  # path of the secret
  path: clusters/dell7040/infrastructure/cert-manager

  # dest k8s secret
  destination:
    name: cloudflare-api-token-secret
    create: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: cert-manager-vault-auth