# vault-auth.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: cert-manager-vault-auth
  namespace: infrastructure
spec:
  # Kubernetes auth configuration
  kubernetes:
    role: dell7040-cert-manager
    serviceAccount: cert-manager
    audiences:
     - "vault"
  vaultConnectionRef: vault-secrets-operator/default
  method: kubernetes
  mount: kubernetes
