apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infrastructure
helmCharts:
  - name: sealed-secrets
    version: 2.18.5
    releaseName: infrastructure-sealed-secrets-controller
    repo: https://bitnami-labs.github.io/sealed-secrets
    valuesFile: values.yaml
    namespace: infrastructure
