apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-truenas-ssd
provisioner: nfs.csi.k8s.io
parameters:
  server: truenas.lab.definit.co.uk
  share: /mnt/pool-01/kubernetes-ssd
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.2
  - hard
  - noatime
  - nconnect=4